---
- hosts: dev
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: frontend
        image: "romerog1512/frontend:latest"
        state: started
        published_ports:
            - 0.0.0.0:80:80