---
- hosts: dev
  become: True
  tasks:
    - name: install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: frontend
        image: "romerog1512/frontend:latest"
        state: started
        published_ports:
            - 0.0.0.0:80:80